/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /**
   * Read the native screen-capture TCC state without exposing platform
   * details. macOS grants may require a restart before capture is usable.
   */
  preflightAppshotPermission(): AppshotPermission
  /**
   * Ask macOS for screen-capture access. The response is deliberately
   * limited to the authorization state and restart requirement.
   */
  requestAppshotPermission(): AppshotPermission
  /**
   * Open the native window-only sharing picker. The selected filter stays
   * in native renderer state and JavaScript receives only a one-shot token.
   */
  selectAppshotWindow(): Promise<AppshotSelection>
  /**
   * Capture the window selected by `select_appshot_window`. A handle is
   * consumed before capture so it cannot be replayed.
   */
  captureAppshotWindow(handle: string): Promise<Buffer>
  /**
   * Capture the native frontmost target without crossing any source
   * identity through the JavaScript ABI.
   */
  captureFrontmostAppshot(): Promise<Buffer>
  /**
   * Explicitly discard a selected source handle. Disposal is idempotent so
   * callers can clean up cancelled UI flows safely.
   */
  disposeAppshotWindow(handle: string): void
  /**
   * Register a renderer-lifetime opaque global-shortcut token. Platform
   * installation is intentionally owned by the native renderer, never by
   * React state or the retained tree.
   */
  registerGlobalShortcut(shortcut: string): string
  /** Remove one renderer-local shortcut registration. */
  unregisterGlobalShortcut(token: string): void
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /** Open the platform-native single-directory picker. Cancellation returns null. */
  promptForDirectory(): Promise<string | null>
  /** Open a URL through GPUI's platform owner. */
  openUrl(url: string): void
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns array of destroyed IDs
   * so JS can clean up event handlers for the entire subtree.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /**
   * Set a custom prop on an element (for non-div/text elements like input, editor, diff).
   * Key is the prop name, value is JSON-encoded.
   */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. Returns JSON string or null. */
  getCustomProp(id: number, key: string): string | null
  /** Signal that a batch of mutations is complete. Triggers re-render. */
  commitMutations(): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["removeChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style } | "{styleJson}"]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",      id, "key", value | "{valueJson}"]
   *   ["setCustomPropValue", id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /** Whether JavaScript must drive the native event loop with tick(). */
  requiresTick(): boolean
  getWindowSize(): WindowSize
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  /** Feed terminal output directly to the retained native emulator. */
  terminalWrite(elementId: number, dataBase64: string): void
  /** Reset the retained native terminal emulator without changing its measured viewport. */
  terminalReset(elementId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /** Scroll a child into view by its index in the children list. */
  scrollToItem(elementId: number, index: number): void
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  simulateClick(x: number, y: number, button?: number | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null): void
  /** Simulate space-separated keys through GPUI's production input path. */
  simulateKeystrokes(keystrokes: string): void
  /** Simulate one key-down event while preserving its parsed modifiers. */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /** Simulate one key-up event while preserving its parsed modifiers. */
  simulateKeyUp(keystroke: string): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

/**
 * GPU-backed GPUI test renderer. Uses VisualTestAppContext (real Metal
 * rendering on macOS) with TestDispatcher for deterministic scheduling.
 * Same GpuixView and rendering pipeline as production.
 *
 * Usage from JS:
 *   const r = new TestGpuixRenderer()
 *   r.createElement(1, "div")
 *   r.setRoot(1)
 *   r.commitMutations()
 *   r.flush()                  // triggers GpuixView::render() via Metal
 *   r.simulateClick(50, 50)    // dispatches through GPUI hit testing
 *   const events = r.drainEvents()
 *   r.captureScreenshot("/tmp/test.png")  // saves rendered UI as PNG
 */
export declare class TestGpuixRenderer {
  constructor()
  /**
   * Deterministic appshot permission state. This double never opens a
   * system picker or captures a real window.
   */
  preflightAppshotPermission(): AppshotPermission
  requestAppshotPermission(): AppshotPermission
  setAppshotPermission(granted: boolean): void
  setAppshotSelection(selected: boolean): void
  selectAppshotWindow(): Promise<AppshotSelection>
  captureAppshotWindow(handle: string): Promise<Buffer>
  captureFrontmostAppshot(): Promise<Buffer>
  disposeAppshotWindow(handle: string): void
  registerGlobalShortcut(shortcut: string): string
  unregisterGlobalShortcut(token: string): void
  /**
   * Test-only native event injection. This keeps global-shortcut dispatch
   * under the same native event owner as production Carbon delivery rather
   * than inventing a JavaScript callback registry.
   */
  triggerGlobalShortcut(token: string): void
  /** Test hosts model cancellation without opening a platform dialog. */
  promptForDirectory(): Promise<string | null>
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns destroyed IDs
   * so JS can clean up event handlers.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /** Set a custom prop on an element (for non-div/text elements like input, editor, diff). */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. */
  getCustomProp(id: number, key: string): string | null
  /** Feed terminal output directly to the retained native emulator. */
  terminalWrite(elementId: number, dataBase64: string): void
  /** Reset the retained native terminal emulator without changing its measured viewport. */
  terminalReset(elementId: number): void
  /**
   * Signal that a batch of mutations is complete.
   * In tests, this is a no-op — flush() handles the actual re-render.
   */
  commitMutations(): void
  /**
   * Apply a batch of mutations in a single FFI call.
   * Same format as GpuixRenderer::apply_batch (string op names).
   * Returns accumulated destroyed IDs from all destroyElement ops.
   */
  applyBatch(json: string): Array<number>
  /**
   * Notify the view entity and run GPUI until parked.
   * This triggers GpuixView::render() → build_element() → GPUI layout.
   * Must be called after mutations and before simulating events (GPUI's
   * hit testing requires elements to be laid out).
   */
  flush(): void
  /**
   * Simulate a click at the given window coordinates.
   * Dispatches MouseDown + MouseUp through GPUI's input pipeline,
   * which triggers the same event handlers as production.
   * IMPORTANT: Call flush() before this — hit testing requires laid-out elements.
   */
  simulateClick(x: number, y: number): void
  /**
   * Simulate key strokes through GPUI's input pipeline.
   * Format: space-separated keys, e.g. "a", "enter", "cmd-shift-p".
   * The focused element receives keyDown/keyUp events.
   */
  simulateKeystrokes(keystrokes: string): void
  /**
   * Commit text through the focused element's platform input handler.
   * This is the production IME insertion path, not a synthesized key event.
   */
  simulateInput(input: string): void
  /**
   * Simulate a single key down event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Unlike simulate_keystrokes, this dispatches ONLY a KeyDownEvent —
   * no automatic KeyUpEvent follows. Use with simulate_key_up for
   * fine-grained key event testing.
   */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /**
   * Simulate a single key up event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Pairs with simulate_key_down for fine-grained key event testing.
   */
  simulateKeyUp(keystroke: string): void
  /**
   * Simulate a mouse move to the given coordinates.
   * pressed_button: optional mouse button held during move (0=left, 1=middle, 2=right).
   * Used to simulate drag events.
   */
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null): void
  /**
   * Focus an element by its numeric ID.
   * The element must have a FocusHandle (created by sync_focus_handles when
   * the element has keyDown, keyUp, focus, or blur listeners).
   * Call flush() before this so the element tree and focus handles exist.
   */
  focusElement(id: number): void
  /**
   * Simulate a mouse down event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseDown(x: number, y: number, button?: number | undefined | null): void
  /**
   * Simulate a mouse up event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseUp(x: number, y: number, button?: number | undefined | null): void
  /**
   * Simulate a scroll wheel event at the given position.
   * delta_x and delta_y are in pixels (negative = scroll up/left).
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection. */
  clearSelection(): void
  /**
   * Syntax-cache counters as `[hits, misses, documents]`.
   *
   * GPUIX rebuilds its whole element tree every frame, so a `<code>` block
   * that misses the cache reparses at frame rate. A test can watch the hit
   * count to catch that regression before a profiler does.
   */
  getSyntaxCacheStats(): Array<number>
  /**
   * Every string painted in the last frame, in paint order.
   *
   * `getAllText()` only sees `<text>` nodes in the retained tree. Native
   * elements such as `<code>` and `<diff>` draw their text inside gpui, so
   * this is the only way to assert on what they actually rendered.
   */
  getPaintedText(): Array<string>
  /**
   * Drag-select from one point to another: mouse down, move, up.
   *
   * A single helper rather than three calls because the listeners that drive
   * selection are registered during **paint**, so a flush must sit between
   * the down and the move. Getting that order wrong silently selects nothing,
   * which is a miserable thing to debug from JS.
   */
  dragSelect(x1: number, y1: number, x2: number, y2: number): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   * Call flush() after to apply the offset and re-render.
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   * Call flush() after to apply and re-render.
   */
  scrollToItem(elementId: number, index: number): void
  /** `"hidden"` | `"minimal"` | `"full"`. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  /**
   * Capture a screenshot of the current rendered state and save as PNG.
   * macOS only — requires Metal GPU rendering via VisualTestAppContext.
   */
  captureScreenshot(path: string): void
  /**
   * Return and clear all collected events since the last drain.
   * Events are collected synchronously — no event loop queuing.
   */
  drainEvents(): Array<EventPayload>
  /** Get all text content in the tree (depth-first order). */
  getAllText(): Array<string>
  /** Find element IDs matching the given type (e.g. "div", "text"). */
  findByType(elementType: string): Array<number>
  /** Check if an element has a specific event listener. */
  hasEventListener(id: number, eventType: string): boolean
  /** Get the text content of an element. */
  getText(id: number): string | null
  /** Get the full tree as JSON for snapshot testing. */
  getTreeJson(): string
  /** Tree JSON with last-paint bounds. Used by the automation locators. */
  getAutomationTree(): string
  /** Last painted bounds for an element, or null if it was not painted. */
  getElementBounds(id: number): Array<number> | null
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  /** Get the root element ID, or null if no root is set. */
  getRootId(): number | null
}

/**
 * Only the permission decision crosses the native ABI. `restart_required`
 * communicates the TCC transition without exposing platform error details.
 */
export interface AppshotPermission {
  status: AppshotPermissionStatus
  restartRequired: boolean
}

/**
 * Closed, native-owned privacy status vocabulary. Platform failures never
 * cross this boundary as strings.
 */
export declare const enum AppshotPermissionStatus {
  Granted = 'granted',
  Missing = 'missing'
}

/**
 * The picker result deliberately has no source metadata. A handle is present
 * only for a selected source and becomes invalid after its first capture or
 * explicit disposal.
 */
export interface AppshotSelection {
  status: AppshotSelectionStatus
  handle?: string
}

/**
 * Closed picker result vocabulary. A selected source is represented only by
 * an opaque one-shot handle.
 */
export declare const enum AppshotSelectionStatus {
  Selected = 'selected',
  Cancelled = 'cancelled'
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Final normalized primary-pane size. Populated by `<split-view>` only
   * after a native drag commits; pointer moves never cross the FFI boundary.
   */
  ratio?: number
  /**
   * Committed serializable layout emitted by `<dock-workspace>`. Native
   * pointer tracking never crosses the FFI boundary; this is sent only
   * after a semantic mutation commits.
   */
  layout?: string
  /** Base64-encoded bytes emitted by `<terminal>` keyboard input. */
  dataBase64?: string
  /** Terminal viewport row count emitted after native measurement. */
  rows?: number
  /** Terminal viewport column count emitted after native measurement. */
  cols?: number
  modifiers?: EventModifiers
}

export interface WindowOptions {
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
}

export interface WindowSize {
  width: number
  height: number
}
